kind: Secret
apiVersion: v1
metadata:
  name: demo-secret
  namespace: demo-namespace
type: Opaque
data:
  database-username: dXNlcm5hbWU= # echo -n 'username' | base64
  database-password: cGFzc3dvcmQ= # echo -n 'password' | base64
