kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-web-deployment
  namespace: demo-namespace
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demo
  
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: web
          image: mongo-express
          ports:
          - containerPort: 8081
          env:
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: demo-config
                key: database-url
          - name: ME_CONFIG_MONGODB_PORT
            valueFrom:
              configMapKeyRef:
                name: demo-config
                key: database-port
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: demo-secret
                key: database-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: demo-secret
                key: database-password
