steps:
  - dataFrameName: orders
    sql:
      SELECT
        CAST(eventOriginal.id AS BIGINT) AS `order_id`,
        eventOriginal.version AS `order_version`,
        enrichedData.orderSource AS `order_source`,
        'FILL' AS `fill_type`,
        fill.id AS `fill_id`,
        fill.requestId AS `request_id`,
        fill.price AS `price`,
        fill.sideRate AS `side_rate`,
        fill.volume AS `volume`,
        fill.quoteId AS `quote_id`,
        fill.tradeId AS `trade_id`,
        fill.version AS `version`,
        fill.traderId AS `trader_id`,
        CAST(${batch_id} AS BIGINT) AS batch_id,
        CAST(date_format(current_timestamp(), 'yyyyMMddHHmmss') AS BIGINT) AS `cdh_ingestion_time`,
        element_at(split(input_file_name(), '/'), -1) AS filename,
        CAST(${load_date} as INT) AS load_date
      FROM
        raw_data
      LATERAL VIEW OUTER
        explode(eventOriginal.fills) AS fill

output:
  - dataFrameName: orders
    outputType: File
    format: parquet
    outputOptions:
      saveMode: Append
      path: validated/orders
      partitionBy:
        - batch_id
        - cdh_ingestion_time
