metrics:
  - /metorikku/metric.yaml            
inputs:
  raw_data:
    file:
      path: /metorikku/data/json/*.json
      format: json
      schemaPath: /metorikku/data/schema/schema.json
      options:
        multiLine: true
output:
  file:
    dir: /metorikku/data/output/

# If set to true, triggers Explain before saving
explain: true

# Shows a Preview of the output
showPreviewLines: 42

# Prints the query after running it
showQuery: true

# Caches the step before each preview
cacheOnPreview: true

# Set Log Level : ALL, DEBUG, ERROR, FATAL, INFO, OFF, TRACE, WARN
logLevel: WARN

# Set Application Name to have app name prefix in spark instrumentation counters
appName: appName

# Optional: controls caching and counting on each output (default is true)
cacheCountOnOutput: false
