steps:
  - dataFrameName: orders
    sql:
      SELECT
        CAST(order.id AS BIGINT) AS `order_id`,
        order.version AS `order_version`,
        order.source AS `order_source`,
        item.id AS `item_id`,
        123 AS `batch_id`
        CAST(date_format(current_timestamp(), 'yyyyMMddHHmmss') AS BIGINT) AS `process_time`
      FROM
        raw_data
      LATERAL VIEW OUTER
        explode(order.itens) AS item

output:
  - dataFrameName: orders
    outputType: File
    format: parquet
    outputOptions:
      saveMode: Append
      path: s3_bucket/orders
      partitionBy:
        - batch_id
        - process_time
